FROM registry.access.redhat.com/ubi10/python-312-minimal:latest

ENV PYTHONUNBUFFERED=1 \
    APP_MODULE=app:app \
    PORT=8080

EXPOSE 8080

USER 0
COPY requirements.txt /tmp/src/requirements.txt
COPY src/ /tmp/src/
RUN /usr/bin/fix-permissions /tmp/src
USER 1001

RUN /usr/libexec/s2i/assemble

CMD ["/usr/libexec/s2i/run"]
